In [5]:
import numpy as np
import pandas as pd

from relay import read_results

results = read_results("data/Apr25_27thAn_set1.shtml")
results.head()

   Place Div/Tot Division Guntime Nettime Min/Mile        MPH
0      1   1/362    M2039   30:43   30:42     4:57  12.121212
1      2   2/362    M2039   31:36   31:36     5:06  11.764706
2      3   3/362    M2039   31:42   31:42     5:07  11.726384
3      4   4/362    M2039   32:28   32:27     5:14  11.464968
4      5   5/362    M2039   32:52   32:52     5:18  11.320755

In [9]:
speeds = results["MPH"].values
my_result = results.query("Nettime == '42:44'")
my_result

    Place Div/Tot Division Guntime Nettime Min/Mile       MPH
96     97  26/256    M4049   42:48   42:44     6:53  8.716707

In [11]:
my_speed = speeds[96]
my_speed

np.float64(8.716707021791768)

In [14]:
(speeds <= my_speed).sum()

np.int64(1537)

In [21]:
((speeds <= my_speed).sum()/results["MPH"].count()) * 100

np.float64(94.12124923453766)

In [23]:
((speeds <= my_speed)).mean()

np.float64(0.9412124923453766)

In [ ]:
def percentile_rank(x, seq):
    return (seq <= x).mean()*100

my_division = results.query("Division == 'M4049' ")
my_division_speed =