In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from empiricaldist import FreqTab

In [3]:
ftab = FreqTab.from_seq([1,2,2,3,5])
n = ftab.sum()
pmf = ftab/n
pmf

1    0.2
2    0.4
3    0.2
5    0.2
Name: , dtype: float64

In [8]:
from empiricaldist import Pmf

pmf = Pmf.from_seq([1,2,2,3,5])
pmf

1    0.2
2    0.4
3    0.2
5    0.2
Name: , dtype: float64

In [10]:
mean = np.sum(pmf.ps * pmf.qs) #expected value
mean

np.float64(2.6)

In [11]:
pmf.mean()

np.float64(2.6)

In [12]:
deviations = pmf.qs - mean
deviations

array([-1.6, -0.6,  0.4,  2.4])

In [13]:
var = np.sum(pmf.ps * deviations **2)
var

np.float64(1.84)

In [38]:
ranges = pd.interval_range(start = 5, end = 50, freq = 5, closed = "left")
ranges.name = "class_size"
data = pd.DataFrame(index= ranges)
data["count"] = [8,8,14,4,6,12,8,3,2]
sizes = ranges.left + 2
n = data["count"].sum()
data["prob"] = data["count"]/n
s = data["prob"]*sizes
s.sum()

np.float64(23.692307692307693)

In [24]:
counts = data["count"]
pmf_actual = Pmf(counts, sizes, name="actual")
pmf_actual.normalize()
pmf_actual.mean()

np.float64(23.692307692307693)

In [36]:
(pmf_actual.ps )

array([0.12307692, 0.12307692, 0.21538462, 0.06153846, 0.09230769,
       0.18461538, 0.12307692, 0.04615385, 0.03076923])